PC=fpc $^ -o$@

clean :
	rm -f kube
	rm -f linia
	rm -f smile
	rm -f q1
	rm -f q2
	rm -f q3
	rm -f q4

linia : linia.pas
	$(PC)

kube : kube.pas
	$(PC)

smile : smile.pas
	$(PC)

q1 : qwer.pas
	$(PC)

q2 : q2.pas
	$(PC)

q3 : q3.pas
	$(PC)

q4 : q4.pas
	$(PC)
